# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonScript\PythonWorkspace\easyTest\tool\project\ui_designer\configCenter.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 600)
        Dialog.setMinimumSize(QtCore.QSize(780, 600))
        Dialog.setMaximumSize(QtCore.QSize(780, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/cog.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 761, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(160, 10, 60, 20))
        self.label.setObjectName("label")
        self.lineEdit_project = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_project.setGeometry(QtCore.QRect(220, 10, 450, 20))
        self.lineEdit_project.setReadOnly(True)
        self.lineEdit_project.setObjectName("lineEdit_project")
        self.pushButton_open1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open1.setGeometry(QtCore.QRect(680, 10, 70, 20))
        self.pushButton_open1.setObjectName("pushButton_open1")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 141, 90))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(159, 40, 591, 60))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 161, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget_testplan = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_testplan.setGeometry(QtCore.QRect(10, 20, 141, 401))
        self.listWidget_testplan.setObjectName("listWidget_testplan")
        self.pushButton_createtestplan = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_createtestplan.setGeometry(QtCore.QRect(10, 430, 60, 23))
        self.pushButton_createtestplan.setObjectName("pushButton_createtestplan")
        self.pushButton_removetestplan = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_removetestplan.setGeometry(QtCore.QRect(90, 430, 60, 23))
        self.pushButton_removetestplan.setObjectName("pushButton_removetestplan")
        self.groupBox_testcase = QtWidgets.QGroupBox(Dialog)
        self.groupBox_testcase.setGeometry(QtCore.QRect(180, 130, 591, 461))
        self.groupBox_testcase.setObjectName("groupBox_testcase")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_testcase)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 490, 101))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_ff = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_ff.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.checkBox_ff.setChecked(True)
        self.checkBox_ff.setObjectName("checkBox_ff")
        self.checkBox_ch = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_ch.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.checkBox_ch.setObjectName("checkBox_ch")
        self.checkBox_ie = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_ie.setGeometry(QtCore.QRect(10, 70, 50, 20))
        self.checkBox_ie.setObjectName("checkBox_ie")
        self.lineEdit_ffremote = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_ffremote.setEnabled(False)
        self.lineEdit_ffremote.setGeometry(QtCore.QRect(79, 10, 400, 20))
        self.lineEdit_ffremote.setReadOnly(False)
        self.lineEdit_ffremote.setObjectName("lineEdit_ffremote")
        self.lineEdit_chremote = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_chremote.setEnabled(False)
        self.lineEdit_chremote.setGeometry(QtCore.QRect(80, 40, 400, 20))
        self.lineEdit_chremote.setObjectName("lineEdit_chremote")
        self.lineEdit_ieremote = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_ieremote.setEnabled(False)
        self.lineEdit_ieremote.setGeometry(QtCore.QRect(80, 70, 400, 20))
        self.lineEdit_ieremote.setObjectName("lineEdit_ieremote")
        self.pushButton_createtestcase = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_createtestcase.setGeometry(QtCore.QRect(10, 430, 70, 23))
        self.pushButton_createtestcase.setObjectName("pushButton_createtestcase")
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_up.setGeometry(QtCore.QRect(90, 430, 50, 23))
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_down.setGeometry(QtCore.QRect(150, 430, 50, 23))
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_removetestcase = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_removetestcase.setGeometry(QtCore.QRect(210, 430, 61, 23))
        self.pushButton_removetestcase.setObjectName("pushButton_removetestcase")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_testcase)
        self.groupBox_5.setGeometry(QtCore.QRect(500, 20, 81, 91))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_filecmp = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_filecmp.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.pushButton_filecmp.setObjectName("pushButton_filecmp")
        self.pushButton_dircmp = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_dircmp.setGeometry(QtCore.QRect(10, 50, 60, 30))
        self.pushButton_dircmp.setObjectName("pushButton_dircmp")
        self.pushButton_allused = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_allused.setGeometry(QtCore.QRect(280, 430, 61, 23))
        self.pushButton_allused.setObjectName("pushButton_allused")
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_reset.setGeometry(QtCore.QRect(350, 430, 61, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_testcase)
        self.tabWidget.setGeometry(QtCore.QRect(0, 120, 491, 301))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_testcase)
        self.groupBox_3.setGeometry(QtCore.QRect(500, 120, 80, 331))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_createscript = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_createscript.setGeometry(QtCore.QRect(10, 210, 60, 30))
        self.pushButton_createscript.setObjectName("pushButton_createscript")
        self.pushButton_createparam = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_createparam.setGeometry(QtCore.QRect(10, 250, 60, 30))
        self.pushButton_createparam.setObjectName("pushButton_createparam")
        self.pushButton_createscene = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_createscene.setGeometry(QtCore.QRect(10, 90, 60, 30))
        self.pushButton_createscene.setObjectName("pushButton_createscene")
        self.pushButton_removescene = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_removescene.setGeometry(QtCore.QRect(10, 130, 60, 30))
        self.pushButton_removescene.setObjectName("pushButton_removescene")
        self.pushButton_copyscene = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_copyscene.setGeometry(QtCore.QRect(10, 170, 60, 30))
        self.pushButton_copyscene.setObjectName("pushButton_copyscene")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_save.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_edit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_edit.setGeometry(QtCore.QRect(10, 290, 60, 30))
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_test = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_test.setGeometry(QtCore.QRect(10, 50, 60, 30))
        self.pushButton_test.setObjectName("pushButton_test")
        self.pushButton_openfile = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_openfile.setGeometry(QtCore.QRect(420, 430, 70, 23))
        self.pushButton_openfile.setObjectName("pushButton_openfile")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_project, self.pushButton_open1)
        Dialog.setTabOrder(self.pushButton_open1, self.listWidget_testplan)
        Dialog.setTabOrder(self.listWidget_testplan, self.pushButton_createtestplan)
        Dialog.setTabOrder(self.pushButton_createtestplan, self.pushButton_removetestplan)
        Dialog.setTabOrder(self.pushButton_removetestplan, self.checkBox_ff)
        Dialog.setTabOrder(self.checkBox_ff, self.lineEdit_ffremote)
        Dialog.setTabOrder(self.lineEdit_ffremote, self.checkBox_ch)
        Dialog.setTabOrder(self.checkBox_ch, self.lineEdit_chremote)
        Dialog.setTabOrder(self.lineEdit_chremote, self.checkBox_ie)
        Dialog.setTabOrder(self.checkBox_ie, self.lineEdit_ieremote)
        Dialog.setTabOrder(self.lineEdit_ieremote, self.pushButton_createtestcase)
        Dialog.setTabOrder(self.pushButton_createtestcase, self.pushButton_up)
        Dialog.setTabOrder(self.pushButton_up, self.pushButton_down)
        Dialog.setTabOrder(self.pushButton_down, self.pushButton_removetestcase)
        Dialog.setTabOrder(self.pushButton_removetestcase, self.pushButton_allused)
        Dialog.setTabOrder(self.pushButton_allused, self.pushButton_reset)
        Dialog.setTabOrder(self.pushButton_reset, self.pushButton_edit)
        Dialog.setTabOrder(self.pushButton_edit, self.pushButton_save)
        Dialog.setTabOrder(self.pushButton_save, self.pushButton_filecmp)
        Dialog.setTabOrder(self.pushButton_filecmp, self.pushButton_dircmp)
        Dialog.setTabOrder(self.pushButton_dircmp, self.pushButton_test)
        Dialog.setTabOrder(self.pushButton_test, self.pushButton_createscript)
        Dialog.setTabOrder(self.pushButton_createscript, self.pushButton_createparam)
        Dialog.setTabOrder(self.pushButton_createparam, self.textBrowser)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置中心"))
        self.label.setText(_translate("Dialog", "项目目录："))
        self.pushButton_open1.setText(_translate("Dialog", "打开..."))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ff007f;\">EasyTest</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; color:#aa00ff;\">配置中心</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">友情提示：编辑后请保存.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("Dialog", "1.测试方案"))
        self.pushButton_createtestplan.setText(_translate("Dialog", "创建方案"))
        self.pushButton_removetestplan.setText(_translate("Dialog", "移除方案"))
        self.groupBox_testcase.setTitle(_translate("Dialog", "2.测试用例套件"))
        self.checkBox_ff.setText(_translate("Dialog", "Firefox"))
        self.checkBox_ch.setText(_translate("Dialog", "Chrome"))
        self.checkBox_ie.setText(_translate("Dialog", "IE"))
        self.pushButton_createtestcase.setText(_translate("Dialog", "增加一行"))
        self.pushButton_up.setText(_translate("Dialog", "上移"))
        self.pushButton_down.setText(_translate("Dialog", "下移"))
        self.pushButton_removetestcase.setText(_translate("Dialog", "移除一行"))
        self.pushButton_filecmp.setText(_translate("Dialog", "文件对比"))
        self.pushButton_dircmp.setText(_translate("Dialog", "目录对比"))
        self.pushButton_allused.setText(_translate("Dialog", "全部启用"))
        self.pushButton_reset.setText(_translate("Dialog", "重置"))
        self.pushButton_createscript.setText(_translate("Dialog", "新建用例"))
        self.pushButton_createparam.setText(_translate("Dialog", "新建参数"))
        self.pushButton_createscene.setText(_translate("Dialog", "新建场景"))
        self.pushButton_removescene.setText(_translate("Dialog", "移除场景"))
        self.pushButton_copyscene.setText(_translate("Dialog", "复制场景"))
        self.pushButton_save.setText(_translate("Dialog", "保存"))
        self.pushButton_edit.setText(_translate("Dialog", "编辑参数"))
        self.pushButton_test.setText(_translate("Dialog", "测试"))
        self.pushButton_openfile.setText(_translate("Dialog", "打开用例"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

