# coding:utf-8
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from script import addPathToPython, initSettings, selectModel

addPathToPython()
initSettings()
selectModel()

from SRC.main import Main

Main('U易联_微信_大转盘.xml').run()
Main('U易联_微信_单图文消息.xml').run()
Main('U易联_微信_多图文消息.xml').run()
Main('U易联_微信_粉丝管理.xml').run()
Main('U易联_微信_公众号绑定.xml').run()
Main('U易联_微信_刮刮乐.xml').run()
Main('U易联_微信_红包.xml').run()
Main('U易联_微信_海报.xml').run()
Main('U易联_微信_流量分析.xml').run()
Main('U易联_微信_模板消息.xml').run()
Main('U易联_微信_渠道档案.xml').run()
Main('U易联_微信_群发消息.xml').run()
Main('U易联_微信_数据总览.xml').run()
Main('U易联_微信_图文分析.xml').run()
Main('U易联_微信_微报名.xml').run()
Main('U易联_微信_微社区.xml').run()
Main('U易联_微信_微调查.xml').run()
Main('U易联_微信_微投票.xml').run()
Main('U易联_微信_微信菜单.xml').run()
Main('U易联_微信_微网站.xml').run()
Main('U易联_微信_微信墙.xml').run()
Main('U易联_微信_文本消息.xml').run()
Main('U易联_微信_现金红包.xml').run()
Main('U易联_微信_消息分析.xml').run()
Main('U易联_微信_用户分析.xml').run()
Main('U易联_微信_砸金蛋.xml').run()
Main('U易联_微信_支付配置.xml').run()
Main('U易联_首页_首页.xml').run()
Main('U易联_设置_操作员管理.xml').run()
Main('U易联_设置_短信设置.xml').run()
Main('U易联_设置_会员体系.xml').run()
Main('U易联_设置_基础设置.xml').run()
Main('U易联_设置_站内消息.xml').run()
Main('U易联_设置_授权信息.xml').run()
Main('U易联_设置_账户信息.xml').run()
Main('U易联_商城_U商城跳转.xml').run()
Main('U易联_商城_店内收银明细.xml').run()
Main('U易联_商城_店铺设置.xml').run()
Main('U易联_商城_订单分析.xml').run()
Main('U易联_商城_分销订单.xml').run()
Main('U易联_商城_分销商.xml').run()
Main('U易联_商城_快递公司.xml').run()
Main('U易联_商城_分销设置.xml').run()
Main('U易联_商城_门店档案.xml').run()
Main('U易联_商城_门店员工.xml').run()
Main('U易联_商城_门店公告.xml').run()
Main('U易联_商城_门店职位.xml').run()
Main('U易联_商城_商品分析.xml').run()
Main('U易联_商城_商品分类.xml').run()
Main('U易联_商城_商品分组.xml').run()
Main('U易联_商城_商品管理.xml').run()
Main('U易联_商城_佣金结算.xml').run()
Main('U易联_商城_佣金提现.xml').run()
Main('U易联_商城_在线促销.xml').run()
Main('U易联_会员_成交时间分析.xml').run()
Main('U易联_会员_储值活动.xml').run()
Main('U易联_会员_储值活动分析.xml').run()
Main('U易联_会员_储值卡管理.xml').run()
Main('U易联_会员_会员等级分布.xml').run()
Main('U易联_会员_会员档案.xml').run()
Main('U易联_会员_会员基本分析.xml').run()
Main('U易联_会员_会员级别.xml').run()
Main('U易联_会员_会员晋级.xml').run()
Main('U易联_会员_渠道销售统计.xml').run()
Main('U易联_会员_营销规则.xml').run()
Main('U易联_会员_优惠劵.xml').run()
Main('U易联_服务_专属客服会话.xml').run()
Main('U易联_服务_专属客服管理.xml').run()
Main('U易联_服务_预约服务.xml').run()
Main('U易联_服务_网店档案.xml').run()
Main('U易联_服务_防伪码分析.xml').run()
Main('U易联_服务_防伪设置.xml').run()
Main('U易联_服务_服务类型.xml').run()
Main('U易联_服务_客服管理.xml').run()
Main('U易联_服务_客服会话.xml').run()
Main('U易联_服务_客服评价.xml').run()
Main('U易联_服务_防伪码档案.xml').run()
